/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package faustoCoppiLabAutomation

import kotlin.test.Test
import kotlin.test.assertNotNull

class MainTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = MainClass()
        assertNotNull(classUnderTest.hello, "app should print hello world !!")
    }
}
