name: 'basic-check'
description: 'action for compile, check, build and test'
runs:
  using: "composite"
  steps:
    - name: Compile
      run: ./gradlew compileKotlin
      shell: bash
    - name: Kotlin style check
      run: ./gradlew ktlintCheck
      shell: bash
    - name: Build
      run: ./gradlew build
      shell: bash
    - name: Test
      run: ./gradlew test
      shell: bash
