FROM adoptopenjdk/openjdk15

COPY "build/libs/athleticpreparation*.jar" ./athleticpreparation/athleticpreparation-latest.jar

CMD [ "java", "-jar",  "./athleticpreparation/athleticpreparation-latest.jar" ]
