name: Project CD/CI
on:
  push:
  pull_request:
    branches:
      - main
      - develop
jobs:
  check-on-push:
    name: Check project on push
    if: ${{ contains(github.event_name, 'push') }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        java: [ 1.8, 15 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Chmode gradlew
        if: ${{ ! contains(matrix.os, 'windows') }}
        run: chmod +x ./gradlew
      - name: ActionChecks
        uses: ./.github/actions
  check-on-pull-request:
    name: Check project on pull request
    if: ${{ contains(github.event_name, 'pull_request') }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-20.04, ubuntu-latest, ubuntu-16.04, macos-latest]
        java: [ 1.8, 11, 12, 13, 14, 15 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Chmode gradlew
        if: ${{ ! contains(matrix.os, 'windows') }}
        run: chmod +x ./gradlew
      - name: ActionChecks
        uses: ./.github/actions
  generate-docs:
    needs: check-on-push
    name: Generate docs and deploy to GithubPages
    if: ${{ contains(github.event_name, 'push') && github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Chmode gradlew
        run: chmod +x ./gradlew
      - name: Generate Dokka docs
        run: ./gradlew dokkaHtmlCollector
      - name: Deploy Dokka docs to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: build/dokka/htmlCollector
  generate-coverage:
    needs: check-on-push
    name: Generate coverage and deploy to Codecov
    if: ${{ contains(github.event_name, 'push') && github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Chmode gradlew
        run: chmod +x ./gradlew
      - name: Generate Jacoco report
        run: ./gradlew test aggregateJacocoReport
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          directory: build/reports/jacoco/aggregate/
          fail_ci_if_error: true
  release:
    needs: check-on-push
    if: ${{ contains(github.ref, 'refs/tags/') }}
    name: Release project on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: re-fetch all tags to get annotations
        run: git fetch --force --tags
      - name: Chmode gradlew
        run: chmod +x ./gradlew
      - name: Assemble dist
        run: ./gradlew assembleDist
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE
            ./build/all-distributions/*.zip
            ./build/all-distributions/*.tar
