name: delivery
on:
  push:
    tags:
      - v*.*.*

jobs:
  Delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Chmode gradlew
        run: chmod +x ./gradlew
      - name: Clean
        run: ./gradlew clean
      - name: Create Jars
        run: ./gradlew jar
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: sbraggion #${{ secrets.DOCKERHUB_USERNAME }}
          password: 55c7d707-0d73-401d-8ca5-091b68947ba0 #${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker-compose file with services
        run: docker-compose -f docker-compose.yml build
      - name: Push to Docker Hub
        run: docker-compose push
