name: workflow
on: 
  push
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: CodeQuality
        run: ./gradlew ktlinCheck 
      - name: Compile
        run: ./gradlew compileKotlin
      - name: Build
        run: ./gradlew build
      - name: Test
        run: ./gradlew test