name: workflow
on: 
  push
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Compile
        run: sudo ./gradlew compileKotlin
      - name: Build
        run: sudo ./gradlew build
      - name: Test
        run: sudo ./gradlew test